config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :machines
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index], export: true
  resources :announcements, only: [:index], export: true
  root to: 'home#index'
end

app/models/machine.rb
class Machine < ApplicationRecord
  after_create_commit  { broadcast_append_to 'machines' }
  after_update_commit  { broadcast_update_to 'machines' }
  after_destroy_commit { broadcast_remove_to 'machines' }
  after_save_commit    { broadcast_update_to 'machines' }
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: %i[ show edit update destroy ]

  # GET /machines or /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1 or /machines/1.json
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines or /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to machine_url(@machine), notice: "Machine was successfully created." }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1 or /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to machine_url(@machine), notice: "Machine was successfully updated." }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1 or /machines/1.json
  def destroy
    @machine.destroy

    respond_to do |format|
      format.html { redirect_to machines_url, notice: "Machine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def machine_params
      params.require(:machine).permit(:name, :user, :address)
    end
end

app/views/machines/_form.html.erb
<%= form_with(model: machine) do |form| %>
  <% if machine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
        <% machine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :user, style: "display: block" %>
    <%= form.text_field :user %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/machines/_machine.html.erb
<div id="<%= dom_id machine %>">
  <p>
    <strong>Name:</strong>
    <%= machine.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= machine.user %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= machine.address %>
  </p>

  <p>
    <%= link_to "Show this machine", machine %>
  </p>

</div>

app/views/machines/edit.html.erb
<h1>Editing machine</h1>

<%= render "form", machine: @machine %>

<br>

<div>
  <%= link_to "Show this machine", @machine %> |
  <%= link_to "Back to machines", machines_path %>
</div>

app/views/machines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Machines</h1>

<%= turbo_stream_from('machines') %>

<div id="machines">
  <% @machines.each do |machine| %>
    <%= turbo_stream_from(machine) %>
    <%= render machine %>
  <% end %>
</div>

<%= link_to "New machine", new_machine_path %>

app/views/machines/new.html.erb
<h1>New machine</h1>

<%= render "form", machine: @machine %>

<br>

<div>
  <%= link_to "Back to machines", machines_path %>
</div>

app/views/machines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @machine %>

<div>
  <%= link_to "Edit this machine", edit_machine_path(@machine) %> |
  <%= link_to "Back to machines", machines_path %>

  <%= button_to "Destroy this machine", @machine, method: :delete %>
</div>